Repository ManageIQ/pg-logical_replication, pull requests merged in 2021-06, with the labels that each got.

#6 [Client] Cache type maps for queries/results
  lib/pg/logical_replication/client.rb
Labels: enhancement, performance

#7 Support providing the db name to the subscriber? method
  lib/pg/logical_replication/client.rb
  spec/client_spec.rb
Labels: enhancement

#11 Drop end of life rubies from travis
  .travis.yml
Labels: technical debt

#12 Update CODEOWNERS
  CODEOWNERS
Labels: documentation

#10 Support create slot shortcut for create subscription to default slot name to sub name
  lib/pg/logical_replication/client.rb
  lib/pg/logical_replication/command_builder.rb
  spec/client_spec.rb
  spec/command_builder_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#13 Drop only publications, subscriptions, and slots from current database in test
  spec/spec_helper.rb
Labels: bug, test
